version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
      - "80:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: renatoreinhold/desafio_emiteai-frontend:latest
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: renatoreinhold/desafio_emiteai-backend:latest
      dockerfile: Dockerfile
    command: >
      ./wait-for-it.sh database 5432 ./wait-for-it.sh rabbit 5672 gradle build
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/appdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - database
      - rabbit

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db_data: